# Generated by Django 5.2.15 on 2026-07-05 03:40

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_module_permission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.SaloonUserManager()),
            ],
        ),
    ]
