# Generated by Django 5.2.15 on 2026-07-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_remove_staff_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary — used for incentive calculations.', max_digits=12),
        ),
    ]
