# Generated by Django 5.2.15 on 2026-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_percent', models.DecimalField(decimal_places=2, default=0, help_text='Incentive percentage applied on target achieved.', max_digits=6)),
                ('salary_times', models.DecimalField(decimal_places=2, default=5, help_text='Number of times of salary used as the monthly target.', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'incentive settings',
                'verbose_name_plural': 'incentive settings',
            },
        ),
    ]
