# Generated by Django 5.2.15 on 2026-07-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_incentive_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivesettings',
            name='incentive_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Incentive percentage applied on target achieved when target is met.', max_digits=6),
        ),
        migrations.CreateModel(
            name='IncentiveSettingsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('salary_times', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
                'indexes': [models.Index(fields=['effective_from'], name='masters_inc_effecti_7cc665_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_versions', to='masters.staff')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
                'indexes': [models.Index(fields=['staff', 'effective_from'], name='masters_sta_staff_i_66d3a8_idx')],
            },
        ),
    ]
