# Generated by Django 5.2.15 on 2026-07-05 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_seed_incentive_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailSaleIncentiveSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_from', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_to', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no upper limit.', max_digits=12, null=True)),
                ('incentive_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'sale_from', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='incentivesettings',
            name='ear_piercing_incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ear piercing incentive in ₹ per unit.', max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettings',
            name='google_review_with_photo_incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Google review with photo — incentive in ₹ per review.', max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettings',
            name='google_review_without_photo_incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Google review without photo — incentive in ₹ per review.', max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettings',
            name='makeup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Make-up incentive as % of make-up amount entered in DSR.', max_digits=6),
        ),
        migrations.AddField(
            model_name='incentivesettings',
            name='membership_card_incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Membership card incentive in ₹ per unit.', max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettings',
            name='watts_incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Watts incentive in ₹ per unit.', max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='ear_piercing_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='google_review_with_photo_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='google_review_without_photo_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='makeup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='membership_card_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='watts_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='RetailSaleIncentiveSlabVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_from', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incentive_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_slabs', to='masters.incentivesettingsversion')),
            ],
            options={
                'ordering': ['sort_order', 'sale_from', 'pk'],
            },
        ),
    ]
