# Generated by Django 5.2.15 on 2026-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_incentive_retail_and_dsr_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivesettings',
            name='ot_incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime (OT) incentive in ₹ per unit.', max_digits=12),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='ot_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
