# Generated by Django 5.2.15 on 2026-07-05 04:02

from decimal import Decimal

from django.db import migrations, models


def migrate_period_profiles(apps, schema_editor):
    IncentiveSettings = apps.get_model("masters", "IncentiveSettings")
    IncentivePeriodProfile = apps.get_model("masters", "IncentivePeriodProfile")
    IncentiveSettingsVersion = apps.get_model("masters", "IncentiveSettingsVersion")
    RetailSaleIncentiveSlab = apps.get_model("masters", "RetailSaleIncentiveSlab")

    settings = IncentiveSettings.objects.first()
    slab_count = RetailSaleIncentiveSlab.objects.count()
    RetailSaleIncentiveSlab.objects.update(period_type="daily")

    def enabled_flags(source):
        service_enabled = Decimal(str(source.incentive_percent or 0)) > 0 or Decimal(
            str(source.salary_times or 0)
        ) > 0
        staff_fields = (
            source.makeup_percent,
            source.google_review_with_photo_incentive,
            source.google_review_without_photo_incentive,
            source.ear_piercing_incentive,
            source.watts_incentive,
            source.membership_card_incentive,
            source.ot_incentive,
        )
        staff_performance_enabled = any(Decimal(str(value or 0)) > 0 for value in staff_fields)
        retail_enabled = slab_count > 0
        return service_enabled, retail_enabled, staff_performance_enabled

    if settings:
        service_enabled, retail_enabled, staff_performance_enabled = enabled_flags(settings)
        IncentivePeriodProfile.objects.update_or_create(
            period_type="daily",
            defaults={
                "service_enabled": service_enabled,
                "incentive_percent": settings.incentive_percent,
                "salary_times": settings.salary_times,
                "retail_enabled": retail_enabled,
                "staff_performance_enabled": staff_performance_enabled,
                "makeup_percent": settings.makeup_percent,
                "google_review_with_photo_incentive": settings.google_review_with_photo_incentive,
                "google_review_without_photo_incentive": settings.google_review_without_photo_incentive,
                "ear_piercing_incentive": settings.ear_piercing_incentive,
                "watts_incentive": settings.watts_incentive,
                "membership_card_incentive": settings.membership_card_incentive,
                "ot_incentive": settings.ot_incentive,
            },
        )

    for period_type in ("weekly", "monthly"):
        IncentivePeriodProfile.objects.get_or_create(period_type=period_type)

    for version in IncentiveSettingsVersion.objects.all():
        service_enabled, retail_enabled, staff_performance_enabled = enabled_flags(version)
        version.period_type = "daily"
        version.service_enabled = service_enabled
        version.retail_enabled = retail_enabled
        version.staff_performance_enabled = staff_performance_enabled
        version.save(
            update_fields=[
                "period_type",
                "service_enabled",
                "retail_enabled",
                "staff_performance_enabled",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_incentive_ot'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentivePeriodProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, unique=True)),
                ('service_enabled', models.BooleanField(default=False)),
                ('incentive_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('salary_times', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('retail_enabled', models.BooleanField(default=False)),
                ('staff_performance_enabled', models.BooleanField(default=False)),
                ('makeup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('google_review_with_photo_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('google_review_without_photo_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ear_piercing_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('watts_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('membership_card_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ot_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['period_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='retailsaleincentiveslab',
            options={'ordering': ['period_type', 'sort_order', 'sale_from', 'pk']},
        ),
        migrations.RemoveIndex(
            model_name='incentivesettingsversion',
            name='masters_inc_effecti_7cc665_idx',
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='retail_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='service_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incentivesettingsversion',
            name='staff_performance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailsaleincentiveslab',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='incentivesettingsversion',
            name='salary_times',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddIndex(
            model_name='incentivesettingsversion',
            index=models.Index(fields=['effective_from', 'period_type'], name='masters_inc_effecti_8a615d_idx'),
        ),
        migrations.RunPython(migrate_period_profiles, migrations.RunPython.noop),
    ]
