# Generated by Django 5.2.15 on 2026-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_branchoutwardline_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardinvoiceline',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Must be set at the branch before stock can be accepted.', null=True),
        ),
    ]
