# Generated by Django 5.2.15 on 2026-07-05 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_managers'),
        ('inventory', '0003_outwardinvoiceline_expiry_date'),
        ('masters', '0012_incentive_period_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='ref_type',
            field=models.CharField(choices=[('GRN', 'GRN'), ('OUTWARD_DISPATCH', 'Outward Dispatch'), ('TRANSFER_RECEIVE', 'Transfer Receive'), ('BRANCH_OUTWARD', 'Branch Outward'), ('OPENING_STOCK', 'Opening Stock')], max_length=20),
        ),
        migrations.CreateModel(
            name='OpeningStockUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_uploads', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stock_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OpeningStockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.openingstockupload')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
