# Generated by Django 5.2.15 on 2026-07-03 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('particulars', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('service_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retail_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upi_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('male_customers', models.PositiveIntegerField(default=0)),
                ('female_customers', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dsr', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('branch', 'report_date')},
            },
        ),
    ]
