# Generated by Django 5.2.15 on 2026-07-03 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('masters', '0002_expenseparticular'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment')], max_length=10)),
                ('particulars', models.CharField(blank=True, help_text='Free text for cash received (receipts)', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expense_particular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_payments', to='masters.expenseparticular')),
            ],
            options={
                'ordering': ['entry_date', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PettyCashEntry',
        ),
    ]
