# Generated by Django 5.2.15 on 2026-07-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dsr_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='particulars',
            field=models.CharField(blank=True, help_text='Free text for cash received (receipts) or opening balance notes', max_length=500),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING', 'Opening Balance'), ('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment')], max_length=10),
        ),
    ]
