# Generated by Django 5.2.15 on 2026-07-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_pettycashtransaction_particulars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsrstaffline',
            name='ear_piercing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dsrstaffline',
            name='google_review_with_photo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dsrstaffline',
            name='google_review_without_photo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dsrstaffline',
            name='makeup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dsrstaffline',
            name='mem_card',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dsrstaffline',
            name='ot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dsrstaffline',
            name='watts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
